name: 'Bintray uploader'
description: 'Upload and publish a binary to Bintray'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  repository:
    description: "Bintray repository name"
    required: true
  package:
    description: "Bintray package name"
    required: true
  version:
    description: "Binary version number"
    required: true
  sourcePath:
    description: "Path to source binary to upload"
    required: true
  username:
    description: "Bintray username"
    required: true
  apiKey:
    description: "Bintray API Key"
    required: true
  override:
    description: "To override an already-published artifact you need to set this to 1"
    required: true
outputs:
runs:
  using: 'node12'
  main: 'index.js'
